apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.app_name }}
spec:
  type:  {{ .Values.service.type }}
  selector:
    app:  {{ .Values.app_name }}
  ports:
  - port:  {{ .Values.ports.port }}
    targetPort:  {{ .Values.ports.containerPort}}